const fs = require('fs');
const path = require('path');

const config = {
  BACKENDLESS_APP_ID: process.env.BACKENDLESS_APP_ID || '',
  BACKENDLESS_JS_KEY: process.env.BACKENDLESS_JS_KEY || '',
  BACKENDLESS_API_URL: process.env.BACKENDLESS_API_URL || 'https://api.backendless.com',
  // 👇 AGGIUNTA QUESTA RIGA 👇
  MAGAZZINO_TABLE_NAME: process.env.MAGAZZINO_TABLE_NAME || 'Magazzino' 
};

const out = `// generated by build - do not edit
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

// Genera il file direttamente nella root del progetto
const outFile = path.join(__dirname, '..', 'env-config.js');

fs.writeFileSync(outFile, out, 'utf8');

console.log('✅ env-config.js generato in', outFile);
