// scripts/generate-config.js
const fs = require('fs');
const path = require('path');

const config = {
  BACKENDLESS_APP_ID: process.env.BACKENDLESS_APP_ID || '',
  BACKENDLESS_JS_KEY: process.env.BACKENDLESS_JS_KEY || '',
  BACKENDLESS_API_URL: process.env.BACKENDLESS_API_URL || 'https://api.backendless.com'
};

const out = `// generated by build - do not edit
window.APP_CONFIG = ${JSON.stringify(config, null, 2)};
`;

const outDir = path.join(__dirname, '..', 'dist');
const outFile = path.join(outDir, 'env-config.js');

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, out, 'utf8');

console.log('✅ env-config.js generato in', outFile);


